# Generated by Django 4.2.4 on 2023-08-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_remove_skill_description_remove_skill_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
