# Generated by Django 4.2.4 on 2023-08-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_portfolio_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='titleValue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
