# Generated by Django 4.2.4 on 2023-08-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_remove_service_value_servicetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviceIcon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
