# Generated by Django 4.2.4 on 2023-08-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_blog_blogtitle_blogtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('blogTitle', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('menus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.menu')),
            ],
        ),
    ]
