# Generated by Django 4.2.4 on 2023-08-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_firstblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
