# Generated by Django 4.2.4 on 2023-08-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_blog_blogid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtitle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
