# Generated by Django 4.2.4 on 2023-08-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_blogtitle_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstBlog',
        ),
    ]
