# Generated by Django 4.2.4 on 2023-08-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_delete_firstblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
