# Generated by Django 4.2.4 on 2023-08-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('productInfo', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
