# Generated by Django 4.2.4 on 2023-08-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_about_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
