# Generated by Django 4.2.4 on 2023-08-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_generalsettings_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
