# Generated by Django 4.2.4 on 2023-08-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_portofliotitle_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolioModal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
