# Generated by Django 4.2.4 on 2023-08-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_portfolio_portfoliomodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='introsection',
            name='introIcon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
